stages:
  - AI_PIPELINE
AI_PIPELINE:
  stage: AI_PIPELINE
  tags:
    - gpu_runner_98
  image: 192.168.1.184/hcita/tiny_ml:1.3
  script:
    - ./scripts/get_ROT.sh
    - python3 ai_pipeline.py --data data/training_cfg/data_config.yaml --epochs 15 --cfg 2head_yolov5n_H05DM011WM0125.yaml  --batch-size 64 --batch-size-tflite 1 --imgch 1 --imgsz 320 --patience 0 --imgsz_tflite 192 --iou-thres 0.5 --conf-thres 0.5 --conf-thres-test 0 --include tflite --device 0 --int8
